colorscheme gruvbox-dark

set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 8,3

add-highlighter global/ number-lines -hlcursor -relative -separator " |" -cursor-separator " >"
add-highlighter global/ show-matching

# remap b to q
map global normal q b
# # variations of b
map global normal Q B
map global normal <a-q> <a-b>
map global normal <a-Q> <a-B>

# unselect on <esc>
map global normal <esc> ";,"

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

# autopairs
plug "alexherbo2/auto-pairs.kak" config %{
	enable-auto-pairs
}

plug "insipx/kak-crosshairs" config %{
	cursorline
}

# fzf
plug "andreyorst/fzf.kak" config %{
	require-module fzf
	require-module fzf-grep
	require-module fzf-file
} defer fzf %{
	set-option global fzf_highlight_command "lat -r {}"
} defer fzf-file %{
	set-option global fzf_file_command "fd . --no-ignore-vcs"
} defer fzf-grep %{
	set-option global fzf_grep_command "fd"
}

map -docstring "open fzf" global user f ": fzf-mode<ret>"

plug "andreyorst/powerline.kak" defer kakoune-themes %{
	powerline-theme gruvbox-darkv
} defer powerline %{
	powerline-format global "git lsp bufname filetype mode_info lsp line_column position"
	set-option global powerline_separator_thin ""
	set-option global powerline_separator ""
} config %{
	powerline-start
}

plug "evanrelf/byline.kak" config %{
	require-module "byline"
}

plug "gustavo-hms/luar" %{
	require-module luar
}

set-option global ui_options terminal_assistant=none

